addons:
  postgresql: "9.1"

# We have to use ../config since Flask files are relative to the *app* not the project
env:
  global:
    - FLASK_APPLICATION_SETTINGS="../config/travis.cfg"

before_script:
  - psql -c "create database travis_ci_test;" -U postgres

language:
  - python

python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - "pip install -r config/dev.reqs.txt"

# command to run tests
script:
  - "python manage.py testall"

notifications:
  email: false
